name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup timezone
        uses: szenius/set-timezone@master
        with:
          timezoneLinux: "Asia/Jakarta"

      - name: Setup the environment
        run: sudo apt-get install elfutils libarchive-tools -y

      - name: Run build script
        run: |
          source build.sh -u
          echo "ZIPNAME=${ZIPNAME}" >> $GITHUB_ENV
          echo "DL_URL=${DL_URL}" >> $GITHUB_ENV

      - name: Setup build date
        run: echo "BUILD_DATE=$(date '+%H:%M %d/%m/%Y')" >> $GITHUB_ENV

      - name: Git variables
        run: |
          HEAD="$(git rev-parse HEAD)"
          COMMIT_POINT="$(git log --pretty=format:'%h: %s' -1)"
          echo "COMMIT_POINT=${COMMIT_POINT}" >> $GITHUB_ENV

      - name: Upload build artifact
        uses: actions/upload-artifact@main
        with:
          name: my-artifact
          path: ${{ env.ZIPNAME }}

      - name: Upload to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          document: ${{ env.ZIPNAME }}
          message: |
             Build date: ⏰ ${{ env.BUILD_DATE }}
             Latest commit: 🎁 ${{ env.COMMIT_POINT }}
